[package]
name = "pool-network"
version = "2.8.1"
authors = [
	"Terraform Labs, PTE.",
	"DELIGHT LABS",
	"Kerber0x <kerber0x@protonmail.com>",
]
edition.workspace = true
description = "Common pool network types"
license = "Apache-2.0"
repository = "https://github.com/White-Whale-Defi-Platform/white-whale-core"
homepage = "https://whitewhale.money"
documentation = "https://docs.whitewhale.money/migaloo-docs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
injective = []

[dependencies]
uint = "0.9.4"
cw20.workspace = true
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
protobuf.workspace = true
white-whale.workspace = true
cosmwasm-schema.workspace = true
