[package]
name = "white-whale-std"
version = "1.1.2"
edition.workspace = true
authors = [
  "Kerber0x <kerber0x@protonmail.com>",
  "0xFable <0xfabledev@gmail.com>",
  "kaimen-sano <kaimen_sano@protonmail.com>",
  "White Whale <info@whitewhale.money>",
]
description = "Common White Whale types and utils"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[features]
backtraces = ["cosmwasm-std/backtraces"]
injective = ["cosmwasm-std/stargate", "cosmwasm-std/cosmwasm_1_1"]
osmosis = ["osmosis_token_factory"]
osmosis_token_factory = ["cosmwasm-std/stargate", "cosmwasm-std/cosmwasm_1_1"]

[dependencies]
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
cosmwasm-schema.workspace = true
cw20.workspace = true
cw2.workspace = true
protobuf.workspace = true
uint.workspace = true
osmosis-std-derive.workspace = true
prost.workspace = true
prost-types.workspace = true
