[package]
name = "terraswap"
version = "2.7.0"
authors = ["Terraform Labs, PTE.", "DELIGHT LABS", "Kerber0x <kerber0x@protonmail.com>"]
edition = "2018"
description = "Common terraswap types"
license = "Apache-2.0"
repository = "https://github.com/terraswap/terraswap"
homepage = "https://terraswap.io"
documentation = "https://docs.terraswap.io"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.13.4" }
cosmwasm-storage = { version = "1.0.0" }
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
schemars = "0.8.10"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
protobuf = { version = "2", features = ["with-bytes"] }
white-whale = { version = "0.1.0", path = "../white-whale" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }